// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

type Project struct {
	ID    int64
	Name  string
	Owner int64
}

type User struct {
	ID       int64
	Name     string
	Email    string
	Password string
}
